[[image]]
path = "wallpapers/file-1.jpg"
hour = 0
min = 0

[[image]]
path = "wallpapers/file-2.jpg"
hour = 2
min = 0

[[image]]
path = "wallpapers/file-3.jpg"
hour = 4
min = 0

[[image]]
path = "wallpapers/file-4.jpg"
hour = 6
min = 0

[[image]]
path = "wallpapers/file-5.jpg"
hour = 8
min = 0

[[image]]
path = "wallpapers/file-6.jpg"
hour = 10
min = 0

[[image]]
path = "wallpapers/file-7.jpg"
hour = 12
min = 0

[[image]]
path = "wallpapers/file-8.jpg"
hour = 14
min = 0

[[image]]
path = "wallpapers/file-9.jpg"
hour = 16
min = 0

[[image]]
path = "wallpapers/file-10.jpg"
hour = 18
min = 0

[[image]]
path = "wallpapers/file-11.jpg"
hour = 20
min = 0

[[image]]
path = "wallpapers/file-12.jpg"
hour = 22
min = 0
